# Basic Information 
title: Pramit Saha
position: Doctoral candidate
affiliation: University of Oxford
affiliation_link: eng.ox.ac.uk
email: pramit.saha (at) eng.ox.ac.uk

# Search Engine Optimization (SEO)
keywords: pramit, pramit saha, saha pramit, saha, Oxford
canonical: https://pramitsaha.github.io/website/
description: Pramit Saha is a doctorate student at University of Oxford. His research lies in deep learning, federated learning, semi-supervised learning, self-supervised learning, domain adaptation, and medical image analysis.



# Links
google_scholar: https://scholar.google.com/citations?user=Sb7d-rsAAAAJ
cv_link: 
github_link: https://github.com/PramitSaha
linkedin:
twitter: 

# Images 
avatar: https://img.yliu.me/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: 
footnote_link: 

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
